CREATE DATABASE CUSTOMERS;
USE CUSTOMERS;

CREATE TABLE PRODUCTS(PRODUCT_ID INT PRIMARY KEY ,PRODUCT_NAME VARCHAR(30), PRICE BIGINT, BRAND_NAME VARCHAR(30),QUANTITY SMALLINT,DISCOUNT_RATE FLOAT);
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,PRICE,BRAND_NAME,QUANTITY,DISCOUNT_RATE) VALUES (
2035,"WASHING MACHINE",40000,"IFB",50,5.5),
(2743,"FRIDGE",28000,"SAMSUNG",80,7.25),
(2436,"AC",180000,"VOLTAS",30,10.0),
(3867,"KITCHEN APPLINCES",20000,NULL,40,6.5);
CREATE TABLE BUYER(BUYER_ID INT PRIMARY KEY,BUYING_PRODUCTS VARCHAR(30),DISCOUNT FLOAT);
INSERT INTO BUYER(BUYER_ID,BUYING_PRODUCTS,DISCOUNT) VALUES (
201,"FRIDGE",7.25),
(202,"AC",10.0),
(203,"SOFA",4.8),
(204,"AIRFRYER",6.5);
SELECT * FROM BUYER;
SELECT MIN(PRICE),MAX(PRICE),COUNT(QUANTITY),AVG(QUANTITY),SUM(PRICE) FROM PRODUCTS;
SELECT PRODUCT_NAME,BRAND_NAME FROM PRODUCTS WHERE PRODUCT_NAME LIKE 'A%';
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE 'W%';
SELECT * FROM PRODUCTS WHERE BRAND_NAME LIKE '___SUNG';
SELECT PRODUCT_ID,PRODUCT_NAME,PRICE,BRAND_NAME FROM PRODUCTS WHERE PRODUCT_ID BETWEEN 2035 AND 2436;
SELECT PRODUCT_NAME ,SUM(QUANTITY) FROM PRODUCTS GROUP BY PRODUCT_NAME;
SELECT QUANTITY AS AMOUNT FROM PRODUCTS;
SELECT APPLIANCES.PRODUCT_NAME FROM PRODUCTS AS APPLIANCES;
SELECT PRODUCT_NAME FROM PRODUCTS INNER JOIN BUYER ON PRODUCTS.DISCOUNT_RATE = BUYER.DISCOUNT;
SELECT PRODUCT_ID FROM PRODUCTS LEFT JOIN BUYER ON PRODUCTS.DISCOUNT_RATE = BUYER.DISCOUNT;
SELECT PRODUCT_NAME FROM PRODUCTS RIGHT JOIN BUYER ON PRODUCTS.DISCOUNT_RATE = BUYER.DISCOUNT;
SELECT * FROM PRODUCTS;
