CREATE DATABASE CUSTOMER;
USE CUSTOMER;

CREATE TABLE PRODUCTS1(PRODUCT_ID INT PRIMARY KEY ,PRODUCT_NAME VARCHAR(30), PRICE BIGINT, BRAND_NAME VARCHAR(30),QUANTITY SMALLINT,DISCOUNT_RATE FLOAT);
INSERT INTO PRODUCTS1(PRODUCT_ID,PRODUCT_NAME,PRICE,BRAND_NAME,QUANTITY,DISCOUNT_RATE) VALUES (
2035,"WASHING MACHINE",40000,"IFB",50,5.5),
(2743,"FRIDGE",28000,"SAMSUNG",80,7.25),
(2436,"AC",180000,"VOLTAS",30,10.0),
(3867,"KITCHEN APPLINCES",20000,NULL,40,6.5);
SELECT (PRICE) FROM PRODUCTS1 WHERE PRODUCT_NAME="WASHING MACHINE" AND PRICE > 20000;
SELECT (PRODUCT_ID) FROM PRODUCTS1 WHERE PRODUCT_NAME="WASHING MACHINE" OR PRICE = 40000;
SELECT (PRODUCT_NAME) FROM PRODUCTS1 WHERE NOT BRAND_NAME = "IFB" AND PRICE =40000;
SELECT * FROM PRODUCTS1 WHERE BRAND_NAME IS NULL;
SELECT * FROM PRODUCTS1 WHERE BRAND_NAME IS NOT NULL;
SELECT MIN(PRICE) FROM PRODUCTS1;
SELECT MAX(PRICE) FROM PRODUCTS1;
SELECT COUNT(PRODUCT_NAME) FROM PRODUCTS1;
SELECT AVG(PRICE) FROM PRODUCTS1;
SELECT SUM(PRICE) FROM PRODUCTS1;
SELECT DISTINCT (BRAND_NAME) FROM PRODUCTS1;
SELECT PRODUCT_NAME,BRAND_NAME FROM PRODUCTS1 WHERE PRODUCT_NAME LIKE 'A%';
SELECT * FROM PRODUCTS1 WHERE PRODUCT_NAME LIKE 'W%';
SELECT * FROM PRODUCTS1 WHERE BRAND_NAME LIKE '___SUNG';
SELECT PRODUCT_NAME,BRAND_NAME FROM PRODUCTS1 LIMIT 3;
SELECT PRODUCT_NAME,PRICE FROM PRODUCTS1 ORDER BY PRODUCT_NAME ASC;
DESC PRODUCTS1;
SELECT BRAND_NAME FROM PRODUCTS1 WHERE BRAND_NAME IN ("IFB");
SELECT PRODUCT_ID,PRODUCT_NAME,PRICE,BRAND_NAME FROM PRODUCTS1 WHERE PRODUCT_ID BETWEEN 2035 AND 2436;
SELECT PRICE AS AMOUNT FROM PRODUCTS1;
SELECT PRODUCT_NAME FROM PRODUCTS1 AS CUSTOM;
SELECT PRODUCT_NAME ,SUM(QUANTITY) FROM PRODUCTS1 GROUP BY PRODUCT_NAME;
SELECT * FROM PRODUCTS1;

