CREATE DATABASE school;
USE school;
CREATE table student(Name varchar(20),rollno int);
INSERT INTO student(Name,rollno) values ("amina",24),("azeya",2),("Devu",3),("Ashii",4);
set sql_safe_updates=0;
UPDATE student
SET Name = "Achu", rollno = 2
WHERE rollno = 3;
DELETE FROM student
WHERE rollno = 24;
SELECT * FROM student;

CREATE DATABASE office;
USE office;
CREATE TABLE EMPLOYEE(EMPID INT,NAME VARCHAR(20),EMPDESIGNATION VARCHAR(25));
INSERT INTO EMPLOYEE(EMPID,NAME,EMPDESIGNATION) VALUES (1,"AMINA","DEVELOPER"),
(2,"AZEYA","DEVELOPER"),
(3,"ASHI","TESTER");
SELECT * FROM EMPLOYEE;
CREATE TABLE STAFF1(STAFFID INT,STAFFNAME VARCHAR(20),SALARY INT);
INSERT INTO STAFF1(STAFFID,STAFFNAME,SALARY) VALUES (254,"AMINA",240000),
(243,"ACHU",60000),
(235,"DEVU",45000);
SELECT * FROM STAFF1;
SELECT NAME
FROM EMPLOYEE
INNER JOIN STAFF1 ON EMPLOYEE.NAME = STAFF1.STAFFNAME;

SELECT EMPID
FROM EMPLOYEE
LEFT JOIN STAFF1 ON EMPLOYEE.EMPID = STAFF1.STAFFNAME;

SELECT SALARY 
FROM STAFF1
RIGHT JOIN EMPLOYEE ON STAFF1.SALARY = EMPLOYEE.NAME;

SELECT EMPID,NAME,STAFFNAME FROM EMPLOYEE FULL JOIN STAFF1 ON EMPID=STAFFNAME;

SELECT EMPID FROM EMPLOYEE UNION SELECT STAFFID FROM STAFF1;




